### PR TITLE
Made compatible with python 3

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
Hi

In this PR I made xbundle compatible with python 3. Previously test suit was not working on python 3. Now it is working on both python version 2.7 and 3

@carsongee @pdpinch @ShawnMilo

### CODE REVIEW

**Comment by pdpinch** [comment]
@ShawnMilo please review when you have time / when you need it

**Comment by ShawnMilo** [comment]
Looks good to me. I'll merge once I independently confirm the output is identical to the old version.

@pdpinch: Are the additional repos you want included in that test, or are the five I'm currently using okay?

    github.mit.edu:mitx/content-devops-0001
    github.mit.edu:mitx/content-mit-801r
    github.mit.edu:mitx/content-mit-801rTCA
    github.mit.edu:mitx/content-mit-801cc
    github.com:edx/edx-demo-course

**Comment by pdpinch** [comment]
If this PR works with the 5 listed here, you should merge it @shawnmilo

Testing the two additional courses should be separate (there's a story for it)

On May 22, 2015, at 12:15 PM, Shawn Milochik <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks good to me. I'll merge once I independently confirm the output is identical to the old version.

@pdpinch<https://github.com/pdpinch>: Are the additional repos you want included in that test, or are the five I'm currently using okay?

github.mit.edu:mitx/content-devops-0001
github.mit.edu:mitx/content-mit-801r
github.mit.edu:mitx/content-mit-801rTCA
github.mit.edu:mitx/content-mit-801cc
github.com:edx/edx-demo-course

**Comment by ShawnMilo** [comment]
It doesn't work with the current test courses. There are a couple of patches I supplied to Amir in his pull request. In addition, there is another issue unrelated to the xbundle changes that makes the output not match. Details in the same conversation:

https://github.com/amir-qayyum-arbisoft/xbundle/pull/2

**Comment by amir-qayyum-khan** [comment]
@ShawnMilo applied your feedback. Can you provide me sample courses for test. Specially the one which are not working with it.

Regarding you below comment which output is correct. Is it messing with LORE, Do you want me to fix output of xbundle?

With these changes (including the two patches I just posted), the output is identical in Python 2. However, it's different in Python 3. The only difference I've noticed so far is that in Python 2 you see this:

```xml
 <file filename="overview.html"/>
```

Notice the self-closing tag.

In Python 3, you get:

```xml
       <file filename="overview.html">&lt;section class="about"&gt;
   &lt;h2&gt;About this course&lt;/h2&gt;
   &lt;p&gt;8.01, Classical Mechanics, is the first of MIT's introductory physics courses. It is a 12 unit calculus-based physics subject covering basic mechanics. It satisfies the General Institute Requirement for physics. This subject taught using the TEAL (Technology-Enabled Active Learning) format which features students working in groups of three, discussing concepts, solving problems, and doing table-top experiments with the aid of computer data acquisition and analysis. We estimate that it will take you 12 hours per week to do well in this course.&lt;/p&gt;
 &lt;/section&gt;
 
 &lt;section class="sections"&gt;
   &lt;h2&gt;List of sections and times&lt;/h2&gt;
   &lt;table&gt;
     &lt;col style="width:15%"/&gt;
     &lt;col style="width:25%"/&gt;
```

This example is heavily truncated; it actually includes the entire contents of the file, followed by:

```xml
</file>
```

My uneducated guess is that this is due to a difference in behavior of the `lxml` package in Python 3. The output seems more correct, because otherwise this data is missing from the xbundle entirely.

**Comment by ShawnMilo** [comment]
Try github.mit.edu:mitx/content-mit-801r if you have access to it. So far the only ones I've tried that have the problem are under mitx. If you can't access it I'll try to find a public course with the same issue.

**Comment by pdpinch** [comment]
Sorry Amir. You won't be able to access that repo. It's on MIT's github enterprise server and you need an MIT Kerberos account to use it.

I can set one up, but it will take a day or two. 

----------------
I am mobile.

**Comment by amir-qayyum-khan** [comment]
@ShawnMilo please find public course if you it is comfortable for you. OR i can wait for few days as @pdpinch said account will take some time.

**Comment by ShawnMilo** [comment]
@amir-qayyum-khan @pdpinch Disregard. The discrepancy is actually due to an undiagnosed unicode handling bug in the Python 2 version that was _fixed_ by switching to Python 3. I'll send an update to fix it for Python 2.

**Comment by ShawnMilo** [comment]
This fixes the issue. It shouldn't affect the output in Python 3. It will add to the output in Python 2, because imported HTML with unicode characters will now be correctly imported.

Specifically, several of the files I tested failed to import `overview.html` in `about`, which worked properly in Python 3.

```diff
diff --git xbundle/__init__.py xbundle/__init__.py
index f77c13c..b3a51df 100644
--- xbundle/__init__.py
+++ xbundle/__init__.py
@@ -166,6 +166,7 @@ class XBundle(object):
         self.import_metadata_from_directory(path)
         self.import_course_from_directory(path)
 
+
     def import_metadata_from_directory(self, path):
         """
         Load policies.
@@ -186,8 +187,9 @@ class XBundle(object):
         # Load "about" files.
         for afn in glob(join(path, 'about/*')):
             try:
-                with open(afn) as data:
-                    self.add_about_file(basename(afn), data.read())
+                with open(afn, "rb") as data:
+                    self.add_about_file(
+                        basename(afn), data.read().decode("utf-8"))
             except ValueError as err:
                 log.warning("Failed to add file %s, error=%s", afn, err)
 
@@ -421,8 +423,12 @@ class XBundle(object):
                 # Moved "if" statement after the "open" statement, so we
                 # no longer create zero-byte files here.
                 if fxml.text not in (None, ""):
-                    with open(join(adir, filename), 'w') as output:
-                        output.write(fxml.text)
+                    try:
+                        to_write = fxml.text.encode("utf-8")
+                    except UnicodeEncodeError:
+                        to_write = fxml.text
+                    with open(join(adir, filename), 'wb') as output:
+                        output.write(to_write)
             except IOError as err:
                 log.error(
                     'failed to write about file %s, error %s',
```

**Comment by amir-qayyum-khan** [comment]
applied patch @ShawnMilo 

cc @pdpinch

**Comment by ShawnMilo** [comment]
I tested this again today and it was good in Python 2 and Python 3. After this branch is merged, the output in Python 2 will be different than it used to be in Python 2 in same cases. Those cases are when an `about` file (such as `overview.html`) contained unicode characters. The old version would try/except and ignore the file. The new version loads it properly.

The short version is that after this merge, the output will be _more_ correct in Python 2.

**Pull request merged**
