### PR TITLE
add split_test to list of descriptor tags

### PR DESCRIPTION
**Pull request by coleshaw**
Adding support for xbundle to recognize split_test components.

### CODE REVIEW

**Comment by pdpinch** [comment]
Can you remind me what a split_test is?

**Comment by coleshaw** [comment]
`split_test` is the OLX term for content experiments (A/B testing):
http://edx.readthedocs.org/projects/edx-open-learning-xml/en/latest/content-experiments/content_experiments_add.html

**Comment by pdpinch** [comment]
Is there a particular course you've been using to test this with?

**Comment by coleshaw** [comment]
I’ve been using a stripped down version of 8.MReV that the authors use to create individual components (which are later assembled into MReV). You could also use MReV as a test case. If you just need a minimal test case, it’s also fairly easy to set one up in Studio and export it (like the attached)

**Comment by coleshaw** [comment]
Surprise, my file got stripped out. I’ll add it to the repo and include it in the PR.

**Comment by pdpinch** [comment]
@amir-qayyum-khan could you take a look at this tomorrow or Friday?

**Comment by amir-qayyum-khan** [comment]
Working  :+1: 

cc @pdpinch

**Comment by pdpinch** [comment]
@cjshawMIT I should have thought of this earlier, but we shouldn't include course content in public repositories like this one. It exposes answers to problems. 

Can you remove the file, rebase and force push? 

Once you've done that, tag me and I'll merge it.

**Comment by coleshaw** [comment]
@pdpinch  The file I uploaded has no real course content, it's just a dummy course I created in Studio with a single chapter > sequential > split_test > verticals > two of the built-in Open edX problems...

**Comment by pdpinch** [comment]
Perfect. Sorry for the false alarm. 

Would you mind squashing your commits anyway?

**Comment by coleshaw** [comment]
@pdpinch Okay, squashed. Thanks!

**Comment by pdpinch** [comment]
Thanks for the rebase @cjshawMIT 

It looks like Travis choked. I'll try running it again.

**Comment by pdpinch** [comment]
We've had test failures across repos because we didn't pin pylint. That's probably what's happening here.

**Comment by coleshaw** [comment]
Superceded by PR #52. Closing...

**Pull request closed without merging**
