### PR TITLE
account for course.xml as symlink

### PR DESCRIPTION
**Pull request by coleshaw**
There is a bug in XBundle when you try to convert a class which uses a symlink for `course.xml` and points to the file in `roots/` -- these might be from latex2edx? The issue arises when you programmatically extract the .zip file using Python, you get an XMLSyntaxError, because Python's `zipfile` library extracts the symlink as an XML file with a text path instead of the symlink. I've seen this in courses like 8.01x and 16.101x (first run). To reproduce, use the included file.

Error (when using the provided file with the original code):

Python 2.7.5 (default, Mar  9 2014, 22:15:05)
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> > > import zipfile
> > > from xbundle import XBundle
> > > zipf = zipfile.ZipFile('tests/data/2015_CourseSymlink.zip', 'r')
> > > zipf.extractall('test_out')
> > > bundle = XBundle()
> > > bundle.import_course_from_directory('test_out/2015_CourseSymlink')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "xbundle/**init**.py", line 207, in import_course_from_directory
> > >     elem = etree.parse(join(path, 'course.xml')).getroot()
> > >   File "lxml.etree.pyx", line 3310, in lxml.etree.parse (src/lxml/lxml.etree.c:72517)
> > >   File "parser.pxi", line 1791, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:105979)
> > >   File "parser.pxi", line 1817, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:106278)
> > >   File "parser.pxi", line 1721, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:105277)
> > >   File "parser.pxi", line 1122, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:100227)
> > >   File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94350)
> > >   File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95786)
> > >   File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:94853)
> > > lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

### CODE REVIEW

**Comment by pdpinch** [comment]
Hey @cjshawMIT I'm trying to clean up some old PRs and noticed this has been open for some time. Is it still relevant? 

I'm not sure, but I think the test failures pre-existed your PR.

**Comment by coleshaw** [comment]
@pdpinch with the new edX course formats, I'm not sure if this is still an issue. We're not actively using `xbundle`, unless SRM / OLS / someone picks up the course-authoring-ish tool we prototyped. I do think some of the errors pre-date this PR, but it's unclear to me how they passed originally, since I didn't touch those files that are currently failing...

**Comment by coleshaw** [comment]
@pdpinch I can update these two PRs in any case, and see if I can get them to pass...

**Comment by pdpinch** [comment]
Hey @cjshawMIT, just checking on this. No urgency whatsoever.

**Comment by coleshaw** [comment]
I think I had the imports cleaned up locally, but ran into problems with the `duplicate code` warnings -- linting still doesn't like how the existing tests have similar expected code blocks, so I need to clean that up.

**Comment by coleshaw** [comment]
Superseded by PR# 53, so closing.

**Pull request closed without merging**
